config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  resources :optimistic_items, only: [:edit, :update, :show]
  resources :pessimistic_items, only: [:edit, :update, :show]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/optimistic_item.rb
class OptimisticItem < ApplicationRecord
  # self.locking_column = :custom_lock_column
end

app/models/pessimistic_item.rb
class PessimisticItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pessimistic_item = PessimisticItem.first
    @optimistic_item = OptimisticItem.first
  end
end

app/controllers/optimistic_items_controller.rb
class OptimisticItemsController < ApplicationController
  def index
    @items = OptimisticItem.all
  end

  def edit
    @item = OptimisticItem.find(params[:id])
  end

  def update
    @item = OptimisticItem.find(params[:id])

    if @item.update(item_params)
      redirect_to optimistic_item_path(@item)
    else
      render :edit
    end

  rescue ActiveRecord::StaleObjectError
    render :edit
  end

  def show
    @item = OptimisticItem.find(params[:id])
  end

  private

  def item_params
    params.require(:optimistic_item).permit(:title, :lock_version)
  end
end

app/controllers/pessimistic_items_controller.rb
class PessimisticItemsController < ApplicationController
  def edit
    @item = PessimisticItem.find(params[:id])
  end

  def update
    # @item = PessimisticItem.find(params[:id])

    # @item.with_lock do
    #   if @item.update(item_params)
    #     sleep 5
    #     redirect_to pessimistic_item_path(@item)
    #   else
    #     render :edit
    #   end
    # end

    PessimisticItem.transaction do
      @item = PessimisticItem.lock("FOR UPDATE NOWAIT").find(params[:id])

      if @item.update(item_params)
        sleep 5
        redirect_to pessimistic_item_path(@item)
      else
        render :edit
      end
    end
  rescue ActiveRecord::LockWaitTimeout 
    render :edit
  end

  def show
    @item = PessimisticItem.find(params[:id])
  end
  
  private

  def item_params
    params.require(:pessimistic_item).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/optimistic_items_helper.rb
module OptimisticItemsHelper
end

app/helpers/pessimistic_items_helper.rb
module PessimisticItemsHelper
end

app/views/home/index.html.erb
<%= link_to "Optimisitc item", optimistic_item_path(@optimistic_item) %>
<%= link_to "Pessimistic item", pessimistic_item_path(@pessimistic_item) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OptimisticAndPessimisticLocking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/optimistic_items/edit.html.erb
<%= form_with model: @item, data: {'turbo': false} do |f| %>
  <%= f.hidden_field :lock_version %>
  <%= f.text_field :title %>
  <%= f.submit "Update" %>
<% end %>

app/views/optimistic_items/show.html.erb
<%= @item.title %>

<%= link_to "Edit", edit_optimistic_item_path(@item) %>

app/views/pessimistic_items/edit.html.erb
<%= form_with model: @item, data: {'turbo': false} do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "Update" %>
<% end %>

app/views/pessimistic_items/show.html.erb
<%= @item.title %>

<%= link_to "Edit", edit_pessimistic_item_path(@item) %>